#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:          myexampledriver
# Required-Start:     $syslog $remote_fs $network
# Required-Stop:      $syslog $remote_fs $network
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  Init for myexampledriver
# Description: Docker myexampledriver volume plugin 
### END INIT INFO

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

BASE=$(basename $0)

# modify these in /etc/default/$BASE (/etc/default/dkv-netshare)
myexampledriver=/usr/bin/$BASE
# This is the pid file created/managed by start-stop-daemon
myexampledriver_SSD_PIDFILE=/var/run/$BASE-ssd.pid
myexampledriver_LOGFILE=/var/log/$BASE.log
myexampledriver_OPTS=
myexampledriver_DESC="myexampledriver"

# Get lsb functions
. /lib/lsb/init-functions

if [ -f /etc/default/$BASE ]; then
	. /etc/default/$BASE
fi

# Check docker is present
if [ ! -x $myexampledriver ]; then
	log_failure_msg "$myexampledriver not present or not executable"
	exit 1
fi

fail_unless_root() {
	if [ "$(id -u)" != '0' ]; then
		log_failure_msg "$myexampledriver_DESC must be run as root"
		exit 1
	fi
}

case "$1" in
	start)
		fail_unless_root

		touch "$myexampledriver_LOGFILE"
		chgrp docker "$myexampledriver_LOGFILE"

		
		log_begin_msg "Starting $myexampledriver_DESC: $BASE"
		start-stop-daemon --start --background \
			--no-close \
			--exec "$myexampledriver" \
			--pidfile "$myexampledriver_SSD_PIDFILE" \
			--make-pidfile \
			-- \
				$DKV_NETSHARE_OPTS \
					>> "$myexampledriver_LOGFILE" 2>&1
		log_end_msg $?
		;;

	stop)
		fail_unless_root
		log_begin_msg "Stopping $myexampledriver_DESC: $BASE"
		start-stop-daemon --stop --pidfile "$myexampledriver_SSD_PIDFILE"
		log_end_msg $?
		;;

	restart)
		fail_unless_root
		myexampledriver_pid=`cat "$myexampledriver_SSD_PIDFILE" 2>/dev/null`
		[ -n "$myexampledriver_pid" ] \
			&& ps -p $myexampledriver_pid > /dev/null 2>&1 \
			&& $0 stop
		$0 start
		;;

	force-reload)
		fail_unless_root
		$0 restart
		;;

	status)
		status_of_proc -p "$myexampledriver_SSD_PIDFILE" "$myexampledriver" "$myexampledriver_DESC"
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac
